opsschool/curriculum

deployment_201.rst

Both supervisord and circus are very common choices when deploying Python/Ruby applications.
I'll write about circus later on when I'll have time.

Mentioned supervisord and circus process watchers

---

index.rst
reading_list.rst

Since the scope of the project is only to get junior admins up to speed,
a supplemental reading list of excellent and well-written books seemed
appropriate. This list is only a starting point, as there's plenty of great books out there I have not read personally. :)
What do you folks think of the idea?
As for the table, I don't like RST grid tables because of how much work they are, but it seems the best way to present the information. Totally not tied to it, and would welcome a better approach if there is one.
I haven't added a new sidebar link before, so I'm not sure if I did it right.

Add a supplemental recommended reading list.

---

labs.rst

~~Idempodency~~ => Idempotency : 2 errors
>"Write a bash script to install something as idempodently as possible."
Idempotently would be allowing the install to be repeated on the same system without altered effect. "Repeatably" would be making sure that the same result was produced afterwards on different systems. I'm guessing the later is intended? No changes made because intent is unclear.

s/Idempodency/Idempotency : 2 errors

---

sysadmin_tools.rst

Fixed Typo.

---

sysadmin_tools.rst

For more information:
https://simple.wikipedia.org/wiki/Exempli_gratia

Correct the expression Exempli gratia (eg --> e.g.)

---

networking_201.rst

Replace: Electrical Interference --> Electromagnetic Interference.
Fix typos.

Improve EMI section.

---

programming_201.rst

Fix typo.
Fix capitalization.
Add links to PEP and PEP8.

Fix typos and add links to PEP docs.

---

databases_101.rst

Add missing '$'.
Fix many typos.

Fix typos.

---

disaster_recovery.rst

Added som todo's to make it easier for others to collab.
Added an example on how to identify DR components and component relations.

Added some more information on Disaster Recovery

---

disaster_recovery.rst
meta/contributions.rst

I finally got around to continue on the disaster recovery section. Yay!
Added some notes on prioritizing.

Updated disaster_recovery.rst

---

sysadmin_101.rst

Here's my crack at a developer perspective. Let me know if there are any changes you would like me to make. Thanks for maintaining this super helpful resource :)

added developer story

---

config_management.rst

Added details to section on Puppet.

Puppet Introduction

---

shell_tools_101.rst

In shell_tools_101.rst in Unix Fundamentals 101, I added a section on "The Unix Philosophy" in response to the Todo note: "Mention that the philosophy here is to have many tools which perform a few discrete tasks, and run them together to get what you want."
My contribution was:
The Unix Philosophy
===================
Unix is characterized by its modular design philosophy. Unix programs are small, single purpose tools that can easily be chained together with other Unix programs. This modular approach allows for a much simpler, more flexible system, since you can combine multiple command line programs to solve a unique problem, without having to write a whole new program to get the job done.

Added section on the unix philosophy to shell_tools_101

---

careers.rst

Planning to do some updating, haven't committed before, wanted to make sure I had things set up right (and that someone looks at pull requests! :) )

single typo fix, mostly just testing setup for pull requests

---

package_management_101.rst
shell_tools_101.rst
shells_101.rst

Without the newline the TODO is not being understood by Sphinx

Adds missing newline & grammatical corrections

---

active_directory_201.rst

Add the sections for the Global Catalog and the 5 FSMO roles

Update two sections in Active Directory 201 page

---

sysadmin_101.rst

"ability to useful work" should read "ability to do useful work"

Sentence needs a verb.

---

careers.rst

HPC Engineer

---

README.md
databases_101.rst
logs_101.rst
meta/style_guide.rst
requirements.txt
sysadmin_tools.rst

Bringing this project into a more modern era.
There's still a need to update to Python 3 - but that can wait until this changeset is deployed.

Updates galore

---

filesystems_101.rst

Links in favour: 
https://en.wikipedia.org/wiki/List_of_default_file_systems
https://wiki.archlinux.org/index.php/Installation_guide

Default Filesystem: EXT4 instead of EXT3

---

filesystems_101.rst

Just doing some copy-editing and clarifying some of the information presented in the filesystems page.

Copy-editing filesystems

---

sysadmin_101.rst

There was a TODO requesting more developer perspectives, so I added one.

Add one perspective for developers

---

package_management_101.rst

* Added a note about the new `apt` command that comes in modern systems.
* Added some fundamental commands to upgrade all packages using apt.

Update some information for apt
